Initialize OxOOL online generation 5.

diff --git a/test/Makefile.am b/test/Makefile.am
--- a/test/Makefile.am
+++ b/test/Makefile.am
@@ -2,55 +2,100 @@
 export MAX_CONCURRENCY=4
 AUTOMAKE_OPTION = serial-tests
 
-# unittest: tests that run a captive oxoolwsd as part of themselves.
+# unittest: tests that run a captive coolwsd as part of themselves.
 check_PROGRAMS = fakesockettest
 
-noinst_PROGRAMS = fakesockettest unittest
+noinst_PROGRAMS = fakesockettest unittest unithttplib
+
+include_paths = ${ZLIB_CFLAGS} ${ZSTD_CFLAGS} ${PNG_CFLAGS}
+if ENABLE_SSL
+include_paths += ${OPENSSL_CFLAGS}
+endif
 
 AM_CXXFLAGS = $(CPPUNIT_CFLAGS) -DTDOC=\"$(abs_top_srcdir)/test/data\" \
 	-I${top_srcdir}/common -I${top_srcdir}/net -I${top_srcdir}/wsd -I${top_srcdir}/kit \
-	-pthread -DLOOLWSD_DATADIR='"@LOOLWSD_DATADIR@"' \
-	-DLOOLWSD_CONFIGDIR='"@LOOLWSD_CONFIGDIR@"' \
+	-I${top_srcdir} -I${top_srcdir}/test \
+	-pthread -DCOOLWSD_DATADIR='"@COOLWSD_DATADIR@"' \
+	-DCOOLWSD_CONFIGDIR='"@COOLWSD_CONFIGDIR@"' \
 	-DDEBUG_ABSSRCDIR='"@abs_srcdir@"' \
 	${include_paths}
 
-noinst_LTLIBRARIES = \
-	unit-base.la unit-tiletest.la \
-	unit-integration.la unit-httpws.la unit-crash.la \
-	unit-convert.la unit-typing.la unit-copy-paste.la \
-	unit-timeout.la unit-prefork.la unit-storage.la \
-	unit-admin.la unit-tilecache.la \
-	unit-fuzz.la unit-oob.la unit-http.la unit-oauth.la \
-	unit-wopi.la unit-wopi-saveas.la \
-	unit-wopi-ownertermination.la unit-wopi-versionrestore.la \
-	unit-wopi-documentconflict.la unit_wopi_renamefile.la unit_wopi_watermark.la \
-	unit-tiff-load.la \
-	unit-large-paste.la \
-	unit-paste.la \
-	unit-load-torture.la \
-	unit-rendering-options.la \
-	unit-password-protected.la \
-	unit-render-shape.la \
-	unit-each-view.la \
-	unit-session.la \
-	unit-uno-command.la \
-	unit-load.la \
-	unit-cursor.la \
-	unit-calc.la \
-	unit-php-proxy.la \
+# These are ordered by how long each takes to run.
+# The longest-running tests are put first, the
+# fastest tests are last. This reduces the
+# total time with parallel runs.
+# The time each test takes is logged, looked for
+# 'Finished in' in the `make check` output.
+# When adding new tests, please maintain order.
+all_la_unit_tests = \
+	unit-tiletest.la \
+	unit-wopi-async-slow.la \
+	unit-wopi-stuck-save.la \
 	unit-insert-delete.la \
+	unit-wopi-fail-upload.la \
+	unit-httpws.la \
+	unit-password-protected.la \
+	unit-wopi-ownertermination.la \
+	unit-crash.la \
+	unit-wopi-save-on-exit.la \
+	unit-wopi-documentconflict.la \
+	unit-wopi-fileurl.la \
+	unit-each-view.la \
 	unit-close.la \
+	unit-integration.la \
+	unit-uno-command.la \
+	unit-load-torture.la \
+	unit-copy-paste.la \
+	unit-http.la \
+	unit-wopi-temp.la \
+	unit-wopi.la \
+	unit-storage.la \
+	unit-wopi-saveas-with-encoded-file-name.la \
+	unit_wopi_watermark.la \
+	unit-wopi-crash-modified.la \
+	unit-oauth.la \
+	unit-wopi-saveas.la \
+	unit-calc.la \
+	unit-wopi-languages.la \
+	unit-wopi-versionrestore.la \
+	unit_wopi_renamefile.la \
+	unit-wopi-async-upload-modifyclose.la \
+	unit-convert.la \
+	unit-rendering-options.la \
+	unit-paste.la \
+	unit-large-paste.la \
+	unit-typing.la \
+	unit-wopi-httpredirectloop.la \
+	unit-render-shape.la \
+	unit-cursor.la \
+	unit-session.la \
+	unit-wopi-httpheaders.la \
+	unit-load.la \
+	unit-wopi-lock.la \
+	unit-wopi-unlock.la \
+	unit-wopi-httpredirect.la \
+	unit-wopi-loadencoded.la \
+	unit-prefork.la \
+	unit-render-search-result.la \
+	unit-tiff-load.la \
 	unit-bad-doc-load.la \
 	unit-hosting.la \
-	unit-wopi-loadencoded.la \
-	unit-wopi-temp.la \
-	unit-wopi-httpheaders.la
+	unit-timeout.la \
+	unit-base.la
+#	unit-admin.la
+#	unit-tilecache.la # Empty test.
+
+if ENABLE_LIBFUZZER
+all_la_unit_tests += unit-fuzz.la
+endif
+
+noinst_LTLIBRARIES = ${all_la_unit_tests}
 
 MAGIC_TO_FORCE_SHLIB_CREATION = -rpath /dummy
-AM_LDFLAGS = -pthread -module $(MAGIC_TO_FORCE_SHLIB_CREATION) $(ZLIB_LIBS)
+AM_LDFLAGS = -pthread -module $(MAGIC_TO_FORCE_SHLIB_CREATION) $(ZLIB_LIBS) $(ZSTD_LIBS) ${PNG_LIBS}
 
 if ENABLE_SSL
-AM_LDFLAGS += -lssl -lcrypto
+AM_LDFLAGS += ${OPENSSL_LIBS}
 endif
 
 # We work around some of the mess of using the same sources both on
@@ -60,10 +105,7 @@ endif
 AM_CPPFLAGS = -pthread -I$(top_srcdir) -DBUILDING_TESTS -DLOK_ABORT_ON_ASSERTION
 
 wsd_sources = \
-            ../common/FileUtil.cpp \
-            ../common/Protocol.cpp \
             ../common/SpookyV2.cpp \
-            ../common/Util.cpp \
             ../common/Authorization.cpp \
             ../kit/Kit.cpp \
             ../kit/TestStubs.cpp \
@@ -74,22 +116,42 @@ wsd_sources = \
 
 test_base_source = \
 	TileQueueTests.cpp \
+	RequestDetailsTests.cpp \
+	StringVectorTests.cpp \
 	WhiteBoxTests.cpp \
+	HttpWhiteBoxTests.cpp \
 	DeltaTests.cpp \
+	UtilTests.cpp \
 	WopiProofTests.cpp \
 	$(wsd_sources)
+
+common_sources = \
+	../common/Protocol.cpp \
+	../common/ConfigUtil.cpp \
+	../common/DummyTraceEventEmitter.cpp \
+	../common/Log.cpp \
+	../common/MessageQueue.cpp \
+	../common/Session.cpp \
+	../common/SigUtil.cpp \
+	../common/Unit.cpp \
+	../common/FileUtil.cpp \
+	../common/Util.cpp \
+	../common/StringVector.cpp \
+	../common/TraceEvent.cpp \
+	../wsd/Exceptions.cpp \
+	../net/HttpRequest.cpp \
+	../net/Socket.cpp \
+	../net/NetUtil.cpp \
+	../wsd/Auth.cpp
+
+unithttplib_CPPFLAGS = -I$(top_srcdir) -DBUILDING_TESTS -DSTANDALONE_CPPUNIT -g
+unithttplib_SOURCES = $(common_sources) test.cpp HttpRequestTests.cpp
+unithttplib_LDADD = $(CPPUNIT_LIBS)
 
 unittest_CPPFLAGS = -I$(top_srcdir) -DBUILDING_TESTS -DSTANDALONE_CPPUNIT -g
 unittest_SOURCES = \
     $(test_base_source) \
-    ../common/Log.cpp \
-    ../common/MessageQueue.cpp \
-    ../common/Session.cpp \
-    ../common/SigUtil.cpp \
-    ../common/Unit.cpp \
-    ../common/StringVector.cpp \
-    ../net/Socket.cpp \
-    ../wsd/Auth.cpp \
+	$(common_sources) \
     ../wsd/TestStubs.cpp \
     test.cpp
 
@@ -97,12 +159,15 @@ unittest_LDADD = $(CPPUNIT_LIBS)
 unit_base_la_LIBADD = $(CPPUNIT_LIBS)
 if ENABLE_SSL
 unittest_SOURCES += ../net/Ssl.cpp
+unithttplib_SOURCES += ../net/Ssl.cpp
 else
 unittest_LDADD += -lssl -lcrypto
+unithttplib_LDADD += -lssl -lcrypto
 unit_base_la_LIBADD += -lssl -lcrypto
 endif
 
-fakesockettest_SOURCES = fakesockettest.cpp ../net/FakeSocket.cpp
+fakesockettest_CPPFLAGS = -g
+fakesockettest_SOURCES = fakesockettest.cpp  ../net/FakeSocket.cpp ../common/DummyTraceEventEmitter.cpp ../common/Log.cpp ../common/Util.cpp
 fakesockettest_LDADD = $(CPPUNIT_LIBS)
 
 # old-style unit tests - bootstrapped via UnitClient
@@ -117,10 +182,11 @@ unit_crash_la_SOURCES = UnitClient.cpp httpcrashtest.cpp
 unit_crash_la_LIBADD = $(CPPUNIT_LIBS)
 
 # unit test modules:
-unit_oob_la_SOURCES = UnitOOB.cpp
 unit_http_la_SOURCES = UnitHTTP.cpp
 unit_http_la_LIBADD = $(CPPUNIT_LIBS)
+if ENABLE_LIBFUZZER
 unit_fuzz_la_SOURCES = UnitFuzz.cpp
+endif
 unit_admin_la_SOURCES = UnitAdmin.cpp
 unit_admin_la_LIBADD = $(CPPUNIT_LIBS)
 unit_typing_la_SOURCES = UnitTyping.cpp
@@ -129,31 +195,61 @@ unit_copy_paste_la_SOURCES = UnitCopyPaste.cpp
 unit_copy_paste_la_LIBADD = $(CPPUNIT_LIBS)
 unit_convert_la_SOURCES = UnitConvert.cpp
 unit_timeout_la_SOURCES = UnitTimeout.cpp
+unit_timeout_la_LIBADD = $(CPPUNIT_LIBS)
 unit_prefork_la_SOURCES = UnitPrefork.cpp
+unit_prefork_la_LIBADD = $(CPPUNIT_LIBS)
 unit_storage_la_SOURCES = UnitStorage.cpp
-unit_tilecache_la_SOURCES = UnitTileCache.cpp
+unit_storage_la_LIBADD = $(CPPUNIT_LIBS)
+# unit_tilecache_la_SOURCES = UnitTileCache.cpp
+# unit_tilecache_la_LIBADD = $(CPPUNIT_LIBS)
 unit_oauth_la_SOURCES = UnitOAuth.cpp
 unit_oauth_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_la_SOURCES = UnitWOPI.cpp
 unit_wopi_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_async_upload_modifyclose_la_SOURCES = UnitWOPIAsyncUpload_ModifyClose.cpp
+unit_wopi_async_upload_modifyclose_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_async_slow_la_SOURCES = UnitWOPISlow.cpp
+unit_wopi_async_slow_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_crash_modified_la_SOURCES = UnitWOPICrashModified.cpp
+unit_wopi_crash_modified_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_saveas_la_SOURCES = UnitWOPISaveAs.cpp
 unit_wopi_saveas_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_saveas_with_encoded_file_name_la_SOURCES = UnitWOPISaveAsWithEncodedFileName.cpp
+unit_wopi_saveas_with_encoded_file_name_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_ownertermination_la_SOURCES = UnitWopiOwnertermination.cpp
 unit_wopi_ownertermination_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_versionrestore_la_SOURCES = UnitWOPIVersionRestore.cpp
 unit_wopi_versionrestore_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_documentconflict_la_SOURCES = UnitWOPIDocumentConflict.cpp
 unit_wopi_documentconflict_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_save_on_exit_la_SOURCES = UnitWOPISaveOnExit.cpp
+unit_wopi_save_on_exit_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_stuck_save_la_SOURCES = UnitWOPIStuckSave.cpp
+unit_wopi_stuck_save_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_fail_upload_la_SOURCES = UnitWOPIFailUpload.cpp
+unit_wopi_fail_upload_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_renamefile_la_SOURCES = UnitWOPIRenameFile.cpp
 unit_wopi_renamefile_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_languages_la_SOURCES = UnitWOPILanguages.cpp
+unit_wopi_languages_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_lock_la_SOURCES = UnitWOPILock.cpp
+unit_wopi_lock_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_unlock_la_SOURCES = UnitWOPIUnlock.cpp
+unit_wopi_unlock_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_watermark_la_SOURCES = UnitWOPIWatermark.cpp
 unit_wopi_watermark_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_loadencoded_la_SOURCES = UnitWOPILoadEncoded.cpp
 unit_wopi_loadencoded_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_temp_la_SOURCES = UnitWOPITemplate.cpp
 unit_wopi_temp_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_fileurl_la_SOURCES = UnitWOPIFileUrl.cpp
+unit_wopi_fileurl_la_LIBADD = $(CPPUNIT_LIBS)
 unit_wopi_httpheaders_la_SOURCES = UnitWOPIHttpHeaders.cpp
 unit_wopi_httpheaders_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_httpredirect_la_SOURCES = UnitWOPIHttpRedirect.cpp
+unit_wopi_httpredirect_la_LIBADD = $(CPPUNIT_LIBS)
+unit_wopi_httpredirectloop_la_SOURCES = UnitWOPIHttpRedirectLoop.cpp
+unit_wopi_httpredirectloop_la_LIBADD = $(CPPUNIT_LIBS)
 unit_tiff_load_la_SOURCES = UnitTiffLoad.cpp
 unit_tiff_load_la_LIBADD = $(CPPUNIT_LIBS)
 unit_large_paste_la_SOURCES = UnitLargePaste.cpp
@@ -166,6 +262,8 @@ unit_rendering_options_la_SOURCES = UnitRenderingOptions.cpp
 unit_rendering_options_la_LIBADD = $(CPPUNIT_LIBS)
 unit_password_protected_la_SOURCES = UnitPasswordProtected.cpp
 unit_password_protected_la_LIBADD = $(CPPUNIT_LIBS)
+unit_render_search_result_la_SOURCES = UnitRenderSearchResult.cpp
+unit_render_search_result_la_LIBADD = $(CPPUNIT_LIBS)
 unit_render_shape_la_SOURCES = UnitRenderShape.cpp
 unit_render_shape_la_LIBADD = $(CPPUNIT_LIBS)
 unit_each_view_la_SOURCES = UnitEachView.cpp
@@ -180,8 +278,6 @@ unit_cursor_la_SOURCES = UnitCursor.cpp
 unit_cursor_la_LIBADD = $(CPPUNIT_LIBS)
 unit_calc_la_SOURCES = UnitCalc.cpp
 unit_calc_la_LIBADD = $(CPPUNIT_LIBS)
-unit_php_proxy_la_SOURCES = UnitPHPProxy.cpp
-unit_php_proxy_la_LIBADD = $(CPPUNIT_LIBS)
 unit_insert_delete_la_SOURCES = UnitInsertDelete.cpp
 unit_insert_delete_la_LIBADD = $(CPPUNIT_LIBS)
 unit_close_la_SOURCES = UnitClose.cpp
@@ -197,111 +293,26 @@ else
 SYSTEM_STAMP =
 endif
 
-CLEANUP_COMMAND=true
-#CLEANUP_COMMAND=if test -s ../oxoolwsd; then echo "Cleaning up..." && ../oxoolwsd --disable-lool-user-checking --cleanup --o:logging.file[@enable]=false --o:logging.level=trace; fi
+CLEANUP_COMMAND=if test -s ../coolwsd; then echo "Cleaning up..." && ../coolwsd --disable-cool-user-checking --cleanup --o:logging.level=trace; fi
 
 if HAVE_LO_PATH
 check-local:
-	$(CLEANUP_COMMAND)
-	./fakesockettest
+	@$(CLEANUP_COMMAND)
+	@UNITTEST=1 ./fakesockettest 2> test.log || (cat test.log && /bin/false)
 	@fc-cache "@LO_PATH@"/share/fonts/truetype
+	@echo "Done test check-local"
 
-# FIXME 2: unit-oob.la fails with symbol undefined:
-# UnitWSD::testHandleRequest(UnitWSD::TestRequest, UnitHTTPServerRequest&, UnitHTTPServerResponse&) ,
 TESTS = \
-	unit-base.la unit-tiletest.la \
-	unit-integration.la unit-httpws.la unit-crash.la \
-	\
-	unit-copy-paste.la unit-typing.la unit-convert.la unit-prefork.la unit-tilecache.la unit-timeout.la \
-        unit-oauth.la unit-wopi.la unit-wopi-saveas.la \
-        unit-wopi-ownertermination.la unit-wopi-versionrestore.la \
-        unit-wopi-documentconflict.la unit_wopi_renamefile.la unit_wopi_watermark.la \
-	unit-http.la \
-	unit-tiff-load.la \
-	unit-large-paste.la \
-	unit-paste.la \
-	unit-load-torture.la \
-	unit-rendering-options.la \
-	unit-password-protected.la \
-	unit-render-shape.la \
-	unit-each-view.la \
-	unit-session.la \
-	unit-uno-command.la \
-	unit-load.la \
-	unit-cursor.la \
-	unit-calc.la \
-	unit-insert-delete.la \
-	unit-close.la \
-	unit-bad-doc-load.la \
-	unit-hosting.la \
-	unit-wopi-loadencoded.la \
-	unit-wopi-temp.la \
-	unit-wopi-httpheaders
-# TESTS += unit-admin.test
-# TESTS += unit-storage.test
-
-# Start forced grouping of tests using stamp files
-
-# isolate this one - it's not a happy test.
-group0.log: unit-copy-paste.log
-	touch $@
-
-# group1.log
-unit-crash.log : group0.log
-unit-tiletest.log : group0.log
-unit-insert-delete.log : group0.log
-unit-each-view.log : group0.log
-unit-httpws.log : group0.log
-unit-close.log : group0.log
-unit-wopi-documentconflict.log : group0.log
-unit-prefork.log : group0.log
-unit-wopi-versionrestore.log : group0.log
-unit-wopi-temp.log : group0.log
-unit_wopi_renamefile.log : group0.log
-unit_wopi_watermark.log : group0.log
-unit-wopi.log : group0.log
-unit-wopi-ownertermination.log : group0.log
-unit-load-torture.log : group0.log
-
-unit-wopi-saveas.log : group0.log
-unit-password-protected.log : group0.log
-unit-http.log : group0.log
-unit-tiff-load.log : group0.log
-unit-render-shape.log : group0.log
-unit-oauth.log : group0.log
-unit-large-paste.log : group0.log
-unit-paste.log : group0.log
-unit-rendering-options.log : group0.log
-
-unit-session.log : group0.log
-unit-uno-command.log : group0.log
-unit-load.log : group0.log
-unit-cursor.log : group0.log
-unit-calc.log : group0.log
-unit-bad-doc-load.log : group0.log
-unit-hosting.log : group0.log
-unit-wopi-loadencoded.log : group0.log
-
-unit-integration.log : group0.log
-unit-convert.log : group0.log
-unit-typing.log : group0.log
-unit-tilecache.log : group0.log
-unit-timeout.log : group0.log
-unit-wopi-httpheaders.log: group0.log
-unit-base.log: group0.log
-
-group1.log: unit-crash.log unit-tiletest.log unit-insert-delete.log unit-each-view.log unit-httpws.log unit-close.log unit-wopi-documentconflict.log unit-prefork.log unit-wopi-versionrestore.log unit-wopi-temp.log unit_wopi_renamefile.log unit_wopi_watermark.log unit-wopi.log unit-wopi-ownertermination.log unit-load-torture.log unit-wopi-saveas.log unit-password-protected.log unit-http.log unit-tiff-load.log unit-render-shape.log unit-oauth.log unit-large-paste.log unit-paste.log unit-rendering-options.log unit-session.log unit-uno-command.log unit-load.log unit-cursor.log unit-calc.log unit-bad-doc-load.log unit-hosting.log unit-wopi-loadencoded.log unit-integration.log unit-convert.log unit-typing.log unit-tilecache.log unit-timeout.log unit-base.log unit-wopi-httpheaders.log
-	$(CLEANUP_COMMAND)
-	touch $@
-
-# end forced grouping
+	${all_la_unit_tests} \
+	unithttplib
 
 endif
 
 TEST_EXTENSIONS = .la
-LA_LOG_DRIVER = ${top_srcdir}/test/run_unit.sh
+LA_LOG_DRIVER = ${top_builddir}/test/run_unit.sh
+LOG_DRIVER = ${top_builddir}/test/run_unit_standalone.sh
 
-EXTRA_DIST = data/delta-text.png data/delta-text2.png data/hello.odt data/hello.txt $(test_SOURCES) $(unittest_SOURCES) run_unit.sh
+EXTRA_DIST = data/delta-text.png data/delta-text2.png data/hello.odt data/hello.txt $(test_SOURCES) $(unittest_SOURCES) run_unit.sh run_unit_standalone.sh
 
 check_valgrind: all
 	@fc-cache "@LO_PATH@"/share/fonts/truetype
@@ -311,8 +322,11 @@ check_valgrind: all
 all-local: unittest
 	@echo
 	@echo "Running build-time unit tests.  For more thorough testing, please run 'make check'."
+	@echo "Test output is in `pwd`/test.log and is displayed on failure."
 	@echo
 	@fc-cache "@LO_PATH@"/share/fonts/truetype
-	@UNITTEST=1 ${top_builddir}/test/unittest
-	echo "Done test all-local"
-	$(CLEANUP_COMMAND)
+	@UNITTEST=1 ${top_builddir}/test/unittest 2> test.log || (cat test.log && /bin/false)
+	@echo "Done test all-local"
+	@$(CLEANUP_COMMAND)
+
+.PRECIOUS: $(TEST_LOGS)
diff --git a/test/run_unit.sh.in b/test/run_unit.sh.in
--- a/test/run_unit.sh.in
+++ b/test/run_unit.sh.in
@@ -10,10 +10,20 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 abs_top_builddir="${DIR}/.."
 systemplate_path="@SYSTEMPLATE_PATH@"
 enable_debug="@ENABLE_DEBUG@"
+if test -z "@ENABLE_SETCAP@"; then
+    capabilities=false
+else
+    capabilities=true
+fi
 jails_path="@JAILS_PATH@"
 lo_path="@LO_PATH@"
 valgrind_cmd="valgrind --tool=memcheck --trace-children=no -v --read-var-info=yes"
 verbose=''
+capabilities="@ENABLE_SETCAP@"
+
+if test "h$capabilities" != "htrue"; then
+    capabilities=false
+fi
 
 # Note that these options are used by commands in the Makefile that
 # Automake generates. Don't be mislead by 'git grep' not showing any
@@ -49,15 +59,6 @@ while test $# -gt 0; do
   shift
 done
 
-echo
-echo "Running ${tst}"
-echo "	$cmd_line"
-
-# drop .la suffix
-tst=`echo $tst | sed "s/\.la//"`;
-
-export LOOL_LOGLEVEL=trace
-
 if test "z$enable_debug" != "ztrue"; then
     echo ""
     echo "It is necessary to configure with --enable-debug for unit tests to pass"
@@ -66,42 +67,50 @@ if test "z$enable_debug" != "ztrue"; then
     exit 1;
 fi
 
+# drop .la suffix
+tst=`echo $tst | sed "s/\.la//"`;
+
 # result logging
-echo "Test output is '$test_output'"
 echo > $test_output
 
-echo "Running $tst | $tst_log ...";
+printf "\nRunning $tst | $tst_log | $test_output $cmd_line\n";
+echo > $tst_log
 if ${trace} \
-       ${abs_top_builddir}/loolwsd --o:sys_template_path="$systemplate_path" \
-       --o:child_root_path="$jails_path" \
-                                   --o:storage.filesystem[@allow]=true \
-                                   --o:logging.level=trace \
-                                   --o:ssl.key_file_path="${abs_top_builddir}/etc/key.pem" \
-                                   --o:ssl.cert_file_path="${abs_top_builddir}/etc/cert.pem" \
-                                   --o:ssl.ca_file_path="${abs_top_builddir}/etc/ca-chain.cert.pem" \
-                                   --o:admin_console.username=admin --o:admin_console.password=admin \
-                                   --o:storage.ssl.enable=false \
-                                   --unitlib="${abs_top_builddir}/test/.libs/$tst.so" 2> "$tst_log"; then
-        echo "Test $tst passed."
-        echo ":test-result: PASS $tst" >> $test_output
+       ${abs_top_builddir}/coolwsd --o:sys_template_path="$systemplate_path" \
+				   --o:child_root_path="$jails_path" \
+				   --o:security.capabilities="${capabilities}" \
+				   --o:storage.filesystem[@allow]=true \
+				   --o:logging.level=trace \
+				   --o:ssl.key_file_path="${abs_top_builddir}/etc/key.pem" \
+				   --o:ssl.cert_file_path="${abs_top_builddir}/etc/cert.pem" \
+				   --o:ssl.ca_file_path="${abs_top_builddir}/etc/ca-chain.cert.pem" \
+				   --o:admin_console.username=admin --o:admin_console.password=admin \
+				   --o:storage.ssl.enable=false \
+				   --unattended \
+				   --unitlib="${abs_top_builddir}/test/.libs/$tst.so" 2> "$tst_log" 1>&2; then
+	echo "Test $tst passed. Finished in ${SECONDS}s."
+	echo ":test-result: PASS $tst" >> $test_output
 else
+	echo "Test $tst FAILED. Finished in ${SECONDS}s."
 	cat $tst_log
-        echo "============================================================="
-        echo "Test failed on unit: $tst re-run with:"
-        echo "   $ gdb --args ${abs_top_builddir}/loolwsd --o:sys_template_path=\"$systemplate_path\" \\"
-        echo "         --o:child_root_path=\"$jails_path\" \\"
-        echo "         --o:storage.filesystem[@allow]=true \\"
-        echo "         --o:storage.ssl.enable=false \\"
-        echo "         --o:logging.level=trace \\"
-        echo "         --o:ssl.key_file_path=\"${abs_top_builddir}/etc/key.pem\" \\"
-        echo "         --o:ssl.cert_file_path=\"${abs_top_builddir}/etc/cert.pem\" \\"
-        echo "         --o:ssl.ca_file_path=\"${abs_top_builddir}/etc/ca-chain.cert.pem\" \\"
-        echo "         --o:admin_console.username=admin --o:admin_console.password=admin \\"
-        echo "         --unitlib=\"${abs_top_builddir}/test/.libs/$tst.so\""
+	echo "============================================================="
+	echo "Test failed on $tst after ${SECONDS}s. Re-run with (remove --unattended to run without gdb and get prompted):"
+	echo "   $ gdb --args ${abs_top_builddir}/coolwsd --o:sys_template_path=\"$systemplate_path\" \\"
+	echo "         --o:child_root_path=\"$jails_path\" \\"
+	echo "         --o:security.capabilities=\"${capabilities}\" \\"
+	echo "         --o:storage.filesystem[@allow]=true \\"
+	echo "         --o:logging.level=error\\" # logs and gdb don't go well together
+	echo "         --o:ssl.key_file_path=\"${abs_top_builddir}/etc/key.pem\" \\"
+	echo "         --o:ssl.cert_file_path=\"${abs_top_builddir}/etc/cert.pem\" \\"
+	echo "         --o:ssl.ca_file_path=\"${abs_top_builddir}/etc/ca-chain.cert.pem\" \\"
+	echo "         --o:admin_console.username=admin --o:admin_console.password=admin \\"
+	echo "         --o:storage.ssl.enable=false \\"
+	echo "         --unattended \\"
+	echo "         --unitlib=\"${abs_top_builddir}/test/.libs/$tst.so\""
 	echo ""
 	echo "   $ less $tst_log # for detailed failure log files"
-        echo "============================================================="
-        echo ":test-result: FAIL $tst" >> $test_output
+	echo "============================================================="
+	echo ":test-result: FAIL $tst" >> $test_output
 fi
 
 # vim:set shiftwidth=4 expandtab:
