除了 loleaflet 外，其餘程式碼與資料與 LibreOffice master 同步

diff --git a/oxoolwsd-systemplate-setup b/oxoolwsd-systemplate-setup
--- a/oxoolwsd-systemplate-setup
+++ b/oxoolwsd-systemplate-setup
@@ -1,20 +1,25 @@
 #!/bin/bash
+#set -x
 
-test $# -eq 3 || { echo "Usage: $0 <chroot template directory for system libs to create> <LO installation directory> <OxOOL extensions directory>"; exit 1; }
-
+test $# -eq 2 || { echo "Usage: $0 <chroot template directory for system libs to create> <LO installation directory>"; exit 1; }
 
 # No provision for spaces or other weird characters in pathnames. So sue me.
 
 CHROOT=$1
 INSTDIR=$2
-EXTDIR=$3
 
 test -d "$INSTDIR" || { echo "No such directory: $INSTDIR"; exit 1; }
 
 mkdir -p $CHROOT || exit 1
 
+# Resolve the real paths, in case they are relative and/or symlinked.
+# INSTDIR_LOGICAL will contain the logical path, if there are symlinks,
+# while INSTDIR is the physical one. Both will most likely be the same,
+# except on systems that have symlinks in the path. We must create
+# both paths (if they are different) inside the jail, hence we need both.
 CHROOT=`cd $CHROOT && /bin/pwd`
-INSTDIR=`cd $INSTDIR && /bin/pwd`
+INSTDIR_LOGICAL=`cd $INSTDIR && /bin/pwd -L`
+INSTDIR=`cd $INSTDIR && /bin/pwd -P`
 
 cd / || exit 1
 
@@ -23,14 +28,12 @@ cd / || exit 1
 # into the template tree of system files for the chroot jails.
 
 # First essential files and shared objects
-find etc/hosts etc/nsswitch.conf etc/resolv.conf \
-     etc/ld.so.* \
+find etc/ld.so.* \
      lib/ld-* lib64/ld-* \
      lib/libnss_* lib64/libnss_* lib/*/libnss_* \
      lib/libresolv* lib64/libresolv* lib/*/libresolv* \
      var/cache/fontconfig \
      etc/fonts \
-     etc/localtime \
      usr/lib/locale/en_US.utf8 \
      usr/lib/locale/C.UTF-8 \
      usr/lib/locale/locale_archive \
@@ -42,7 +45,6 @@ find etc/hosts etc/nsswitch.conf etc/resolv.conf \
 	 -type f 2>/dev/null
 
 find etc/fonts \
-     etc/resolv.conf \
      lib/ld-* lib64/ld-* \
      lib/libnss_* lib64/libnss_* lib/*/libnss_* \
      lib/libresolv* lib64/libresolv* lib/*/libresolv* \
@@ -63,7 +65,36 @@ grep -v dynamic | cut -d " " -f 3 | grep -E '^(/lib|/usr)' | sort -u | sed -e 's
 # This will now copy the file a symlink points to, but whatever.
 cpio -p -d -L $CHROOT
 
-mkdir -p $CHROOT/tmp
+# Link the dynamic files, replacing any existing.
+for file in hosts nsswitch.conf resolv.conf passwd group host.conf timezone localtime
+do
+    #echo "Linking/Copying /etc/$file"
+    # Prefer hard-linking, fallback to just copying (do *not* use soft-linking because that would be relative to the jail).
+    ln -f /etc/$file $CHROOT/etc/ 2> /dev/null || cp /etc/$file $CHROOT/etc/ || echo "Failed to link or copy $file"
+done
+
+# Link dev/random and dev/urandom to ../tmp/dev/.
+# The jail then creates the random device nodes in its /tmp/dev/.
+mkdir -p $CHROOT/dev
+mkdir -p $CHROOT/tmp/dev
+for file in random urandom
+do
+    # This link is relative anyway, so can be soft.
+    ln -f ../tmp/dev/$file $CHROOT/dev/ 2> /dev/null || ln -f -s ../tmp/dev/$file $CHROOT/dev/ || echo "Failed to link dev/$file"
+done
+
+# Create a relative symbolic link within systemplate that points from
+# the path of $INSTDIR (as seen from the jail as an absolute path)
+# to the /lo path, where the instdir of LO will really reside.
+mkdir -p $CHROOT/lo
+# In case the original path is different from
+for path in $INSTDIR $INSTDIR_LOGICAL
+do
+    # Create a soft-link, as it's a relative directory path (can't be a hard-link).
+    INSTDIR_PARENT="$(dirname "$CHROOT/$path")"
+    mkdir -p $INSTDIR_PARENT
+    ln -f -s `realpath --relative-to=$INSTDIR_PARENT $CHROOT/lo` $CHROOT/$path
+done
 
 # /usr/share/fonts needs to be taken care of separately because the
 # directory time stamps must be preserved for fontconfig to trust
@@ -72,7 +103,7 @@ mkdir -p $CHROOT/tmp
 cd $CHROOT || exit 1
 
 mkdir -p usr/share || exit 1
-ln -sf /usr/share/fonts usr/share
+cp -r -p -L /usr/share/fonts usr/share
 
 if [ -h usr/share/fonts/ghostscript ]; then
     mkdir usr/share/ghostscript || exit 1
@@ -89,14 +120,5 @@ if test "z$ENABLE_DEBUG" != "z" -a "z$HOME" != "z"; then
     mkdir -p $CHROOT/$HOME
     test -d $HOME/.fonts && cp -r -p -L $HOME/.fonts $CHROOT/$HOME
 fi
-
-# Unzip extensions to the system template 
-CHROOT_EXTDIR="${CHROOT}/lo/share/extensions"
-find $EXTDIR -name "*.oxt" |
-while read oxt ; do 
-    BASENAME=`basename $oxt`
-    mkdir -p "${CHROOT_EXTDIR}/${BASENAME}"
-    unzip -d "${CHROOT_EXTDIR}/${BASENAME}" "${oxt}" 2>&1>/dev/null
-done
 
 exit 0
