Large updates.

diff --git a/oxoolwsd-systemplate-setup b/oxoolwsd-systemplate-setup
--- a/oxoolwsd-systemplate-setup
+++ b/oxoolwsd-systemplate-setup
@@ -1,14 +1,17 @@
-#!/bin/bash
-#set -x
+#!/usr/bin/env bash
+# set -x
 
 test $# -eq 2 || { echo "Usage: $0 <chroot template directory for system libs to create> <LO installation directory>"; exit 1; }
 
 # No provision for spaces or other weird characters in pathnames. So sue me.
 
+# First parameter is the pathname where this script will create the "systemplate" tree
 CHROOT=$1
+
+# Second parameter is the instdir directory of the LibreOffice installation to be used
 INSTDIR=$2
 
-test -d "$INSTDIR" || { echo "No such directory: $INSTDIR"; exit 1; }
+test -d "$INSTDIR" || { echo "$0: No such directory: $INSTDIR"; exit 1; }
 
 mkdir -p $CHROOT || exit 1
 
@@ -21,6 +24,16 @@ CHROOT=`cd $CHROOT && /bin/pwd`
 INSTDIR_LOGICAL=`cd $INSTDIR && /bin/pwd -L`
 INSTDIR=`cd $INSTDIR && /bin/pwd -P`
 
+if [ ! `uname -s` = "FreeBSD" ]; then
+    CP=cp
+    REALPATH=realpath
+    LOCALBASE=usr/
+else
+    CP=gcp
+    REALPATH=grealpath
+    LOCALBASE=usr/local/
+fi
+
 cd / || exit 1
 
 (
@@ -31,6 +44,7 @@ cd / || exit 1
 find etc/ld.so.* \
      lib/ld-* lib64/ld-* \
      lib/libnss_* lib64/libnss_* lib/*/libnss_* \
+     lib/*/nss/*.so \
      lib/libresolv* lib64/libresolv* lib/*/libresolv* \
      var/cache/fontconfig \
      etc/fonts \
@@ -57,7 +71,7 @@ find $INSTDIR -name 'xpdfimport' |
 while read file; do
     ldd $file 2>/dev/null
 done |
-grep -v dynamic | cut -d " " -f 3 | grep -E '^(/lib|/usr)' | sort -u | sed -e 's,^/,,'
+grep -v dynamic | cut -s -d " " -f 3 | grep -E '^(/lib|/usr)' | sort -u | sed -e 's,^/,,'
 
 ) |
 
@@ -66,11 +80,15 @@ grep -v dynamic | cut -d " " -f 3 | grep -E '^(/lib|/usr)' | sort -u | sed -e 's
 cpio -p -d -L $CHROOT
 
 # Link the dynamic files, replacing any existing.
+rm -f $CHROOT/etc/copied
+mkdir -p $CHROOT/etc/
 for file in hosts nsswitch.conf resolv.conf passwd group host.conf timezone localtime
 do
-    #echo "Linking/Copying /etc/$file"
-    # Prefer hard-linking, fallback to just copying (do *not* use soft-linking because that would be relative to the jail).
-    ln -f /etc/$file $CHROOT/etc/ 2> /dev/null || cp /etc/$file $CHROOT/etc/ || echo "Failed to link or copy $file"
+    # echo "Linking/Copying /etc/$file"
+    # Prefer hard-linking, fallback to just copying (do *not* use symlinking because that would be relative to the jail).
+    # When copying, we must make sure that we copy the source and not a symlink. Otherwise, the source won't be accessible from the jail.
+    # In addition, we flag that at least one file is copied by creating the 'copied' file, so that we do check for updates.
+    ln -f `${REALPATH} /etc/$file` $CHROOT/etc/$file 2> /dev/null || (${CP} --dereference --preserve=all /etc/$file $CHROOT/etc/$file && touch $CHROOT/etc/copied) || echo "$0: Failed to link or copy /etc/$file"
 done
 
 # Link dev/random and dev/urandom to ../tmp/dev/.
@@ -79,8 +97,8 @@ mkdir -p $CHROOT/dev
 mkdir -p $CHROOT/tmp/dev
 for file in random urandom
 do
-    # This link is relative anyway, so can be soft.
-    ln -f ../tmp/dev/$file $CHROOT/dev/ 2> /dev/null || ln -f -s ../tmp/dev/$file $CHROOT/dev/ || echo "Failed to link dev/$file"
+    # This link is relative anyway, so can be symbolic.
+    ln -f ../tmp/dev/$file $CHROOT/dev/ 2> /dev/null || ln -f -s ../tmp/dev/$file $CHROOT/dev/ || echo "$0: Failed to link dev/$file"
 done
 
 # Create a relative symbolic link within systemplate that points from
@@ -90,10 +108,10 @@ mkdir -p $CHROOT/lo
 # In case the original path is different from
 for path in $INSTDIR $INSTDIR_LOGICAL
 do
-    # Create a soft-link, as it's a relative directory path (can't be a hard-link).
+    # Create a symlink, as it's a relative directory path (can't be a hard-link).
     INSTDIR_PARENT="$(dirname "$CHROOT/$path")"
     mkdir -p $INSTDIR_PARENT
-    ln -f -s `realpath --relative-to=$INSTDIR_PARENT $CHROOT/lo` $CHROOT/$path
+    ln -f -s `${REALPATH} --relative-to=$INSTDIR_PARENT $CHROOT/lo` $CHROOT/$path
 done
 
 # /usr/share/fonts needs to be taken care of separately because the
@@ -102,23 +120,23 @@ done
 
 cd $CHROOT || exit 1
 
-mkdir -p usr/share || exit 1
-cp -r -p -L /usr/share/fonts usr/share
+mkdir -p $LOCALBASE/share || exit 1
+${CP} -r -p -L /${LOCALBASE}/share/fonts $LOCALBASE/share
 
-if [ -h usr/share/fonts/ghostscript ]; then
-    mkdir usr/share/ghostscript || exit 1
-    cp -r -p -L /usr/share/ghostscript/fonts usr/share/ghostscript
+if [ -h $LOCALBASE/share/fonts/ghostscript ]; then
+    mkdir $LOCALBASE/share/ghostscript || exit 1
+    ${CP} -r -p -L /$LOCALBASE/share/ghostscript/fonts $LOCALBASE/share/ghostscript
 fi
 
 # Remove obsolete & unused bitmap fonts
-find usr/share -name '*.pcf' | xargs rm -f
-find usr/share -name '*.pcf.gz' | xargs rm -f
+find $LOCALBASE/share -name '*.pcf' | xargs rm -f
+find $LOCALBASE/share -name '*.pcf.gz' | xargs rm -f
 
 # Debugging only hackery to avoid confusion.
 if test "z$ENABLE_DEBUG" != "z" -a "z$HOME" != "z"; then
-    echo "Copying development users's fonts into systemplate"
+    echo "$0: Copying development users's fonts into systemplate"
     mkdir -p $CHROOT/$HOME
-    test -d $HOME/.fonts && cp -r -p -L $HOME/.fonts $CHROOT/$HOME
+    test -d $HOME/.fonts && ${CP} -r -p -L $HOME/.fonts $CHROOT/$HOME
 fi
 
 exit 0
